# Generated by Django 5.0.6 on 2024-05-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classrooms',
            fields=[
                ('email_creator', models.EmailField(max_length=254)),
                ('classroom_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('classroom_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'classrooms',
            },
        ),
    ]
