# Generated by Django 5.0.6 on 2024-05-25 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_announcement_answerslist_attachment_attemptquiz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='creator_email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data'),
        ),
        migrations.AlterField(
            model_name='task',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user_data'),
        ),
        migrations.DeleteModel(
            name='Learner',
        ),
        migrations.RemoveField(
            model_name='user_data',
            name='t_ype',
        ),
        migrations.DeleteModel(
            name='Educator',
        ),
    ]
