# Generated by Django 5.0.6 on 2024-05-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_quiz_email_alter_announcement_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classroom_id',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
